### ISSUE TITLE
Exception in thread "main" de.westnordost.osmapi.common.errors.OsmApiReadResponseException: de.westnordost.osmapi.common.errors.XmlParserException: Error parsing XML at END_TAG </relation>@3997:13 in java.io.InputStreamReader@4079d7b3

### ISSUE THREAD

**Issue by Eljah** [westnordost/osmapi#11]
Hi!

Please take a look at my programm and the exception:

import de.westnordost.osmapi.OsmConnection;
import de.westnordost.osmapi.map.MapDataDao;
import de.westnordost.osmapi.map.data.*;
import de.westnordost.osmapi.map.handler.MapDataHandler;

/**
 * Created by eljah32 on 9/21/2017.
 */
public class ConnectionTester {
    public static void main(String[] args) {
        OsmConnection osm = new OsmConnection(
                "http://api.openstreetmap.org/api/0.6/",
                "BusRouteDataExtractor 1.0", null);

        MapDataDao mapDao = new MapDataDao(osm);

        double LONGITUDE_START = 48.833744;
        double LATITUDE_START = 55.693307;

        double LONGITUDE_STOP = 49.261698;
        double LATITUDE_STOP = 55.897801;

        double currentLong = LONGITUDE_START;
        double currentLat = LATITUDE_START;

        MapDataHandler mapDataHandler = new MapDataHandler() {
            public void handle(BoundingBox boundingBox) {
            }

            public void handle(Node node) {
            }

            public void handle(Way way) {
            }

            public void handle(Relation relation) {
                if (relation.getTags().get("type").equals("route"))
                {
                System.out.println(relation.getTags().get("name"));
                 }
            }
        };

        OsmLatLon min = null;
        OsmLatLon max = null;
        while (currentLat < LATITUDE_STOP) {

            while (currentLong < LONGITUDE_STOP) {
                //System.out.println(currentLat+", "+currentLong);
                min = new OsmLatLon(currentLat, currentLong);
                max = new OsmLatLon(currentLat+0.01, currentLong+0.01);
                BoundingBox kazanBuses = new BoundingBox(min, max);
                mapDao.getMap(kazanBuses, mapDataHandler);

                currentLong=currentLong+0.01;
            }
            currentLong=LONGITUDE_START;
            currentLat=currentLat+0.01;
        }

        //osm.
    }
}

Exception in thread "main" de.westnordost.osmapi.common.errors.OsmApiReadResponseException: de.westnordost.osmapi.common.errors.XmlParserException: Error parsing XML at END_TAG </relation>@3997:13 in java.io.InputStreamReader@4079d7b3
	at de.westnordost.osmapi.OsmConnection.handleResponse(OsmConnection.java:322)
А77 пер. Дуслык – Нефтебаза
	at de.westnordost.osmapi.OsmConnection.makeRequest(OsmConnection.java:191)
	at de.westnordost.osmapi.OsmConnection.makeRequest(OsmConnection.java:142)
	at de.westnordost.osmapi.map.MapDataDao.getMap(MapDataDao.java:194)
	at ConnectionTester.main(ConnectionTester.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: de.westnordost.osmapi.common.errors.XmlParserException: Error parsing XML at END_TAG </relation>@3997:13 in java.io.InputStreamReader@4079d7b3
	at de.westnordost.osmapi.common.XmlParser.doParse(XmlParser.java:64)
	at de.westnordost.osmapi.map.MapDataParser.parse(MapDataParser.java:58)
	at de.westnordost.osmapi.map.MapDataParser.parse(MapDataParser.java:20)
	at de.westnordost.osmapi.OsmConnection.handleResponse(OsmConnection.java:314)
	... 9 more
Caused by: java.lang.NullPointerException
	at ConnectionTester$1.handle(ConnectionTester.java:38)
	at de.westnordost.osmapi.map.MapDataParser.onEndElement(MapDataParser.java:164)
	at de.westnordost.osmapi.common.XmlParser.doParse(XmlParser.java:49)
	... 12 more

**Comment by westnordost** [comment]
So the source exception is
`at de.westnordost.osmapi.map.MapDataParser.onEndElement(MapDataParser.java:164)`

handler is null.
This should be the expection you get if you pass null for the handler in `mapDataDao.getMap`

**Comment by Eljah** [comment]
thanks a lot; I supposed null be never got
