### ISSUE TITLE
Cannot get coordinates of a way element

### ISSUE THREAD

**Issue by manolo** [westnordost/osmapi#34]
)Hi, I have the code below, with a query that returns nodes and ways.
In order to place those ways in the map I need at least one coordinate of the nodes that compose the way.
But querying the service for getting those nodes, if I query only a value I get a null, and querying for a collection it raises an error, probably I'm doing something wrong but couldn't find an answer for the problem.
Please could you explain how to get coordinates of the way objects?

```
    public static void main(String[] args) {
        
        String qry = "[bbox:40.20,-3.5,40.60,-2.5];(node[tourism=attraction];node[tourism=museum];node[historic];way[amenity=place_of_worship];); out;";
        OsmConnection connection = new OsmConnection("https://overpass-api.de/api/", null);
        OverpassMapDataApi overpass = new OverpassMapDataApi(connection);
        
        HashMap<Long, Way> ways = new HashMap<>();
        
        System.err.println("Running QUERY");
        overpass.queryElements(qry, new MapDataHandler() {
            public void handle(Relation relation) {
            }
            public void handle(Way n) {
                System.err.println(">>>>>> WAY " + n.getId());
                System.err.println(">>>>>> FIRST NODE ID " + n.getNodeIds().iterator().next());
                ways.put( n.getNodeIds().iterator().next(), n);
            }
            
            public void handle(Node n) {
                System.err.println(n.getId());
            }
            
            public void handle(BoundingBox bounds) {
            }
        });      
        
        MapDataApi api = new MapDataApi(connection);
        System.err.println("Getting FIRST WAY NODE " + ways.keySet().iterator().next());
        Node node = api.getNode(ways.keySet().iterator().next());
        System.err.println("NODE: " + node); // It returns null always

        System.err.println("Getting WAY NODES"); // This throws an Exception
        api.getNodes(ways.keySet());
    }
```

Exception message is:

```
Exception in thread "main" de.westnordost.osmapi.common.errors.OsmNotFoundException: Not Found (404) - <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL was not found on this server.</p>
<hr>
<address>Apache/2.4.18 (Ubuntu) Server at overpass-api.de Port 443</address>
</body></html>

	at de.westnordost.osmapi.OsmApiErrorFactory.createError(OsmApiErrorFactory.java:28)
	at de.westnordost.osmapi.OsmConnection.handleResponseCode(OsmConnection.java:349)
	at de.westnordost.osmapi.OsmConnection.makeRequest(OsmConnection.java:195)
	at de.westnordost.osmapi.OsmConnection.makeRequest(OsmConnection.java:148)
	at de.westnordost.osmapi.map.MapDataApi.getSomeElements(MapDataApi.java:386)
	at de.westnordost.osmapi.map.MapDataApi.getNodes(MapDataApi.java:306
...
```

**Comment by westnordost** [comment]
MapDataApi requires a connection to the OpenStreetMap API, Overpass is a different API.

However, of you just want the geometry of the ways queried in the overpass query, it should be possible to include that in that query.  I think it was "out geom;" but you need to look that up on the documentation

**Comment by westnordost** [comment]
See OverpassMapDataApi::queryElementsWithGeometry

**Comment by manolo** [comment]
`out geom;` and `OverpassMapDataApi::queryElementsWithGeometry`  worked like a charm. Thanks so much.

**Comment by westnordost** [comment]
De nada. With `out geom;` you only get the geometry though, not the tags, if I remember correctly. Note the javadoc comment for that method (and the overpass documentation)
